server:
  port: 8989

spring:
  application:
    name: fiber
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/fiber
    username: root
    password: fiberpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: info
    sql: info
    root: info

jwt:
  key: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338
