server:
  port: 8989
  error:
    include-stacktrace: NEVER

spring:
  application:
    name: fiber
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/fiber
    username: guest
    password: guest
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

logging:
  level:
    web: info
    sql: info
    root: info

jwt:
  key: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338
  expiretime: 60 #minutes
