server:
  port: 8989
  error:
    include-stacktrace: NEVER

spring:
  application:
    name: fiber
  sql:
    init:
      platform: ${base_platform:postgres}
      mode: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

mysql:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/fiber
    username: root
    password: guest
    driver-class-name: com.mysql.cj.jdbc.Driver

postgres:
  datasource:
    url: ${base_url:localhost}
    username: ${username:guest}
    password: ${password:guest}

jwt:
  key: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338
  expiretime: 120 #minutes
