server:
  port: 8989

spring:
  application:
    name: fiber
  datasource:
    url: jdbc:mysql://localhost:3306/fiber
    username: root
    password: fiberpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: debug
    sql: info
    root: info